SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE reservations;
TRUNCATE TABLE campsites;
ALTER TABLE reservations ALTER COLUMN id RESTART WITH 1;
ALTER TABLE campsites    ALTER COLUMN id RESTART WITH 1;
SET REFERENTIAL_INTEGRITY TRUE;
