DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS campsites;

CREATE TABLE campsites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_number VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    max_people INTEGER
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reservation_date DATE,
    campsite_id BIGINT NOT NULL,
    phone_number VARCHAR(255),
    status VARCHAR(255),
    confirmation_code VARCHAR(6),
    created_at TIMESTAMP,
    CONSTRAINT fk_reservation_campsite FOREIGN KEY (campsite_id) REFERENCES campsites(id)
);
